server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://192.168.211.160:8762/eureka/,http://192.168.211.160:8761/eureka/}

management:
  security:
    enabled: false
zuul:
#  routes:
#    microservice-user: /u2/**
  ignored-services: microservice-eureka
#  ribbon的饥饿加载，解决首次访问慢的问题
  ribbon:
    eager-load:
      enabled: true


